image: Ubuntu2204  # образ для сборки

stack: node 20  # окружение

branches:
  only:
    - master  # ветка git
    - main

cache: off  # кеширование

install:
  - yarn  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - yarn build   # команда сборки

# before_test:
#   - sudo apt-get install chromium-browser

test_script:
  - yarn lint  # скрипт тестирования
  - yarn test 
  

# deploy_script:  # скрипт развёртывания
#   - git config --global credential.helper store
#   - git config --global user.name AppVeyor
#   - git config --global user.email ci@appveyor.com
#   - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
#   - npx gh-pages -d dist -u "appveyor-bot <ci@appveyor>"
